# Transcript sampling / GPT input limits
SAMPLED_TEXT_MAX_CHARS = 12_000
SHORT_VIDEO_THRESHOLD_SEC = 900

# Route-specific transcript caps
CHAPTERS_TRANSCRIPT_MAX_CHARS = 100_000
CHAT_TRANSCRIPT_MAX_CHARS = 120_000

# SubsProvider / curl
SUBS_PROVIDER_CURL_TIMEOUT_SEC = 120
SUBS_PROVIDER_CURL_PROCESS_TIMEOUT_SEC = 125

# AsrProvider
ASR_PROVIDER_INIT_TIMEOUT_SEC = 300
ASR_PROVIDER_POLL_TIMEOUT_SEC = 30

# YouTube metadata
YOUTUBE_META_TIMEOUT_SEC = 15
