/**
 * UI string translations — static dictionary for in-app labels.
 *
 * Content translations (title/summary/chapters-list/transcript) go through
 * the translation API. This file covers short, stable UI labels where the
 * cost/latency of API translation isn't justified.
 *
 * GENERATED — do not hand-edit individual entries unless you also update
 * the source/prompt and re-run scripts/regenerate_ui_strings.py.
 *
 * Tone: casual / conversational. Where a lang distinguishes formal/informal
 * "you", informal is used (matches the friendly product voice).
 */

export const UI_STRINGS = {
  /* ── "Chapters" — section label ── */
  chapters: {
    en: 'Chapters',
    fa: 'فصل‌ها',
    es: 'Capítulos',
    pt: 'Capítulos',
    fr: 'Chapitres',
    zh: '章节',
    de: 'Kapitel',
    ja: 'チャプター',
    ko: '챕터',
    hi: 'अध्याय',
    ar: 'الفصول',
    ru: 'Главы',
    it: 'Capitoli',
    tr: 'Bölümler',
    nl: 'Hoofdstukken',
    pl: 'Rozdziały',
    sv: 'Kapitel',
    da: 'Kapitler',
    fi: 'Jaksot',
    no: 'Kapitler',
    el: 'Κεφάλαια',
    he: 'פרקים',
    th: 'บท',
    vi: 'Chương',
    id: 'Bab',
    ms: 'Bab',
    uk: 'Розділи',
    cs: 'Kapitoly',
    ro: 'Capitole',
    hu: 'Fejezetek',
    bg: 'Глави',
    hr: 'Poglavlja',
    sk: 'Kapitoly',
    sr: 'Poglavlja',
    bn: 'অধ্যায়',
    ta: 'அத்தியாயங்கள்',
    ur: 'ابواب',
    fil: 'Mga Kabanata',
    sw: 'Sura',
    ca: 'Capítols',
    af: 'Hoofstukke',
    et: 'Peatükid',
    lv: 'Nodaļas',
    lt: 'Skyriai',
    sl: 'Poglavja',
    te: 'అధ్యాయాలు',
    mr: 'प्रकरणे',
    gu: 'અધ્યાય',
    kn: 'ಅಧ್ಯಾಯಗಳು',
    ml: 'അധ്യായങ്ങൾ',
    pa: 'ਅਧਿਆਇ',
    si: 'අධ්‍යාය',
    ne: 'अध्यायहरू',
    my: 'အခန်းများ',
    km: 'ជំពូក',
    lo: 'ບົດ',
    'zh-TW': '章節',
    mn: 'Бүлгүүд',
    ku: 'Babetên',
    az: 'Fəsillər',
    uz: 'Bo\'limlar',
    kk: 'Бөлімдер',
    ky: 'Бөлүмдөр',
    tg: 'Бобҳо',
    ka: 'თავები',
    hy: 'Բաժիններ',
    ps: 'برخې',
    am: 'ክፍሎች',
    ha: 'Babi',
    yo: 'Ẹ̀ka',
    ig: 'Isi',
    zu: 'Izahluko',
    xh: 'Izahluko',
    so: 'Cutubyada',
    rw: 'Ibice',
    mg: 'Toko',
    sq: 'Kapitujt',
    mk: 'Поглавја',
    bs: 'Poglavlja',
    is: 'Kaflar',
    mt: 'Kapitli',
    ga: 'Caibidlí',
    cy: 'Penodau',
    gl: 'Capítulos',
    eu: 'Kapituluak',
    be: 'Раздзелы',
    ht: 'Chapit',
    mi: 'Wāhanga',
    sm: 'Mataupu',
    haw: 'Māhele',
    bo: 'དུས་ཚོད་གྲངས།',
    eo: 'Ĉapitroj',
    lb: 'Kapitelen',
    co: 'Capituli',
    su: 'Bab',
    jv: 'Bab',
    ceb: 'Mga Kapitulo',
    gd: 'Caibidealan',
    tt: 'Бүлекләр',
    tk: 'Bölümler',
    wo: 'Kàttan',
    ti: 'ክፍሊት',
    om: 'Boqonnaa',
    sd: 'باب',
    fj: 'Wasewase',
    to: 'Vahe',
  },

  /* ── "Context from RecapShark.com" — header above the context block ── */
  contextHeader: {
    en: 'Context from RecapShark.com',
    fa: 'زمینه از RecapShark.com',
    es: 'Contexto de RecapShark.com',
    pt: 'Contexto do RecapShark.com',
    fr: 'Contexte de RecapShark.com',
    zh: '来自 RecapShark.com 的背景信息',
    de: 'Kontext von RecapShark.com',
    ja: 'RecapShark.comからのコンテキスト',
    ko: 'RecapShark.com에서 가져온 컨텍스트',
    hi: 'RecapShark.com से संदर्भ',
    ar: 'السياق من RecapShark.com',
    ru: 'Контекст с RecapShark.com',
    it: 'Contesto da RecapShark.com',
    tr: 'RecapShark.com\'dan Bağlam',
    nl: 'Context van RecapShark.com',
    pl: 'Kontekst z RecapShark.com',
    sv: 'Sammanhang från RecapShark.com',
    da: 'Kontekst fra RecapShark.com',
    fi: 'Konteksti RecapShark.comista',
    no: 'Kontekst fra RecapShark.com',
    el: 'Πλαίσιο από το RecapShark.com',
    he: 'הקשר מ-RecapShark.com',
    th: 'บริบทจาก RecapShark.com',
    vi: 'Ngữ cảnh từ RecapShark.com',
    id: 'Konteks dari RecapShark.com',
    ms: 'Konteks dari RecapShark.com',
    uk: 'Контекст з RecapShark.com',
    cs: 'Kontext z RecapShark.com',
    ro: 'Context de la RecapShark.com',
    hu: 'Környezet a RecapShark.com-tól',
    bg: 'Контекст от RecapShark.com',
    hr: 'Kontekst s RecapShark.com',
    sk: 'Kontext z RecapShark.com',
    sr: 'Kontekst sa RecapShark.com',
    bn: 'RecapShark.com থেকে প্রেক্ষাপট',
    ta: 'RecapShark.com-இல் இருந்து உள்ளடக்கம்',
    ur: 'RecapShark.com سے سیاق و سباق',
    fil: 'Konteksto mula sa RecapShark.com',
    sw: 'Muktadha kutoka RecapShark.com',
    ca: 'Context de RecapShark.com',
    af: 'Konteks van RecapShark.com',
    et: 'Kontekst RecapShark.com-ist',
    lv: 'Konteksts no RecapShark.com',
    lt: 'Kontekstas iš RecapShark.com',
    sl: 'Kontekst iz RecapShark.com',
    te: 'RecapShark.com నుండి సందర్భం',
    mr: 'RecapShark.com कडून संदर्भ',
    gu: 'RecapShark.com માંથી સંદર્ભ',
    kn: 'RecapShark.com ನಿಂದ ಸನ್ನಿವೇಶ',
    ml: 'RecapShark.com-ൽ നിന്ന് സന്ദർഭം',
    pa: 'RecapShark.com ਤੋਂ ਸੰਦਰਭ',
    si: 'RecapShark.com වෙතින් පසුබිම',
    ne: 'RecapShark.com बाट सन्दर्भ',
    my: 'RecapShark.com မှ အကြောင်းအရာ',
    km: 'បរិបទពី RecapShark.com',
    lo: 'ບົດບາດຈາກ RecapShark.com',
    'zh-TW': '來自 RecapShark.com 的背景資訊',
    mn: 'RecapShark.com-с ирсэн агуулга',
    ku: 'Naveroka ji RecapShark.com',
    az: 'RecapShark.com-dan Kontekst',
    uz: 'RecapShark.com\'dan kontekst',
    kk: 'RecapShark.com сайтынан контекст',
    ky: 'RecapShark.com сайтынан контекст',
    tg: 'Мазмун аз RecapShark.com',
    ka: 'კონტექსტი RecapShark.com-დან',
    hy: 'Կոնտեքստը RecapShark.com-ից',
    ps: 'له RecapShark.com څخه سیاق و سباق',
    am: 'ከRecapShark.com የተገኘ እንቅስቃሴ',
    ha: 'Mahallin daga RecapShark.com',
    yo: 'Àkóónú láti RecapShark.com',
    ig: 'Ihe gbasara RecapShark.com',
    zu: 'Uhlaka oluvela ku-RecapShark.com',
    xh: 'Umxholo ovela ku-RecapShark.com',
    so: 'Macnaha laga soo qaatay RecapShark.com',
    rw: 'Amakuru aturutse kuri RecapShark.com',
    mg: 'Toe-javatra avy amin\'ny RecapShark.com',
    sq: 'Konteksti nga RecapShark.com',
    mk: 'Контекст од RecapShark.com',
    bs: 'Kontekst sa RecapShark.com',
    is: 'Samhengið frá RecapShark.com',
    mt: 'Kuntest minn RecapShark.com',
    ga: 'Comhthéacs ó RecapShark.com',
    cy: 'Cyd-destun o RecapShark.com',
    gl: 'Contexto de RecapShark.com',
    eu: 'Testuingurua RecapShark.com-etik',
    be: 'Кантэкст з RecapShark.com',
    ht: 'Kontèks soti nan RecapShark.com',
    mi: 'Horopaki mai i RecapShark.com',
    sm: 'Fa\'amatalaga mai RecapShark.com',
    haw: 'Kūlana mai RecapShark.com',
    bo: 'རེ་ཀེཕ་ཤརཀ་དང་ལྡན་པའི་སྐབས་བཅད།',
    eo: 'Kunteksto de RecapShark.com',
    lb: 'Kontekst vu RecapShark.com',
    co: 'Cuntestu da RecapShark.com',
    su: 'Konteks ti RecapShark.com',
    jv: 'Konteks saka RecapShark.com',
    ceb: 'Konteksto gikan sa RecapShark.com',
    gd: 'Co-theacsa bho RecapShark.com',
    tt: 'RecapShark.com-тан контекст',
    tk: 'RecapShark.com-dan Kontekst',
    wo: 'Njuumte ci RecapShark.com',
    ti: 'ኣብ እትሕብር ካብ RecapShark.com',
    om: 'Seensa irraa RecapShark.com',
    sd: 'RecapShark.com تان پسمنظر',
    fj: 'I tukutuku mai RecapShark.com',
    to: 'Kontekisi mei RecapShark.com',
  },

  /* ── Recap intro label (always reads '1 minute' regardless of actual video length — deliberate product choice) ── */
  recapTemplate: {
    en: 'Here\'s your 1 minute recap',
    fa: 'این خلاصه 1 دقیقه‌ای تو هست',
    es: 'Aquí tienes tu resumen de 1 minuto',
    pt: 'Aqui está o seu resumo de 1 minuto',
    fr: 'Voici ton récapitulatif d\'1 minute',
    zh: '这是你的 1 minute 精华',
    de: 'Hier ist deine 1-Minuten-Zusammenfassung',
    ja: '1分間の要約だよ',
    ko: '여기 너의 1분 요약이야',
    hi: 'ये रहा तुम्हारा 1 मिनट का सारांश',
    ar: 'إليك ملخصك في دقيقة واحدة',
    ru: 'Вот твой 1 минутный обзор',
    it: 'Ecco il tuo riassunto di 1 minuto',
    tr: 'İşte 1 dakikalık özetin',
    nl: 'Hier is je 1 minuut samenvatting',
    pl: 'Oto twoje 1 minutowe podsumowanie',
    sv: 'Här är din 1 minutssammanfattning',
    da: 'Her er din 1 minutters opsummering',
    fi: 'Tässä on 1 minuutin yhteenveto',
    no: 'Her er din 1 minutts oppsummering',
    el: 'Ορίστε η ανακεφαλαίωση του 1 λεπτού σου',
    he: 'הנה הסיכום שלך בדקה אחת',
    th: 'นี่คือสรุป 1 นาทีของคุณ',
    vi: 'Đây là tóm tắt 1 phút của bạn',
    id: 'Ini rekap 1 menitmu',
    ms: 'Ini ringkasan 1 minit kamu',
    uk: 'Ось твій 1 minute підсумок',
    cs: 'Tady je tvoje 1 minutové shrnutí',
    ro: 'Iată recapitularea ta de 1 minut',
    hu: 'Itt van az 1 perces összefoglalód',
    bg: 'Ето твоето 1 минутно резюме',
    hr: 'Evo tvoje 1 minute sažetka',
    sk: 'Tu je tvoj 1 minute súhrn',
    sr: 'Evo tvog 1 minute pregleda',
    bn: 'এখানে তোমার 1 minute সারাংশ',
    ta: 'இது உன் 1 நிமிட சுருக்கம்',
    ur: 'یہ رہا تمہارا 1 minute خلاصہ',
    fil: 'Narito ang iyong 1 minute recap',
    sw: 'Hapa ni muhtasari wako wa dakika 1',
    ca: 'Aquí tens el teu resum d\'1 minut',
    af: 'Hier is jou 1 minuut opsomming',
    et: 'Siin on sinu 1 minuti kokkuvõte',
    lv: 'Te ir tavs 1 minūtes kopsavilkums',
    lt: 'Štai tavo 1 minutės santrauka',
    sl: 'Tukaj je tvoj 1 minutni povzetek',
    te: 'ఇదిగో నీ 1 minute సారాంశం',
    mr: 'हे घे, तुझा 1 minute चा सारांश',
    gu: 'આ રહ્યો તમારો 1 મિનિટનો રીકૅપ',
    kn: 'ಇದು ನಿನ್ನ 1 minute ಸಾರಾಂಶ',
    ml: 'ഇവിടെയുണ്ട് നിന്റെ 1 minute സംഗ്രഹം',
    pa: 'ਇਹ ਰਿਹਾ ਤੁਹਾਡਾ 1 minute ਦਾ ਸੰਖੇਪ',
    si: 'මේක තමයි ඔයාගේ 1 minute සාරාංශය',
    ne: 'यहाँ तिम्रो 1 minute को संक्षेप छ',
    my: 'ဒီမှာ 1 minute အကျဉ်းချုပ်ပါ',
    km: 'នេះជាការសង្ខេបរបស់អ្នកក្នុងរយៈពេល 1 នាទី',
    lo: 'ນີ້ແມ່ນການສະຫຼຸບ 1 minute ຂອງເຈົ້າ',
    'zh-TW': '這是你的 1 分鐘摘要',
    mn: 'Энд таны 1 минутын хураангуй байна',
    ku: 'Ew recapê te ya 1 deqeyî',
    az: 'Budur, sənin 1 dəqiqəlik xülasən',
    uz: 'Mana, senga 1 minutlik xulosa',
    kk: 'Міне, сенің 1 минуттық қысқаша мазмұның',
    ky: 'Бул жерде сенин 1 мүнөттүк кыскача баяның',
    tg: 'Ин аст хулосаи 1 дақиқаи ту',
    ka: 'აი შენი 1 წუთიანი შეჯამება',
    hy: 'Ահա քո 1 րոպեանոց ամփոփումը',
    ps: 'دا دی ستا 1 minute لنډیز',
    am: 'እነሆ! የአንድ ደቂቃ አጭር መግለጫህ ነው',
    ha: 'Ga takaitaccen bayani na minti 1',
    yo: 'Èyí ni ìṣàpẹẹrẹ rẹ fún ìṣẹ́jú 1',
    ig: 'Nke a bụ nchịkọta gị nke 1 minute',
    zu: 'Nansi isifinyezo sakho semizuzu engu-1',
    xh: 'Nanku umfanekiso wakho wemizuzu eyi-1',
    so: 'Waa kan soo koobkaaga 1 daqiiqo ah',
    rw: 'Dore incamake yawe y\'iminota 1',
    mg: 'Ity ny famintinana 1 minitra anao',
    sq: 'Ja përmbledhja jote 1 minutëshe',
    mk: 'Еве го твојот резиме од 1 минута',
    bs: 'Evo tvojeg 1 minute sažetka',
    is: 'Hér er 1 mínútu yfirlitið þitt',
    mt: 'Hawnhekk għandek ir-recap ta\' 1 minuta tiegħek',
    ga: 'Seo do achoimre 1 nóiméad',
    cy: 'Dyma dy grynodeb 1 minute',
    gl: 'Aquí tes o teu resumo de 1 minuto',
    eu: 'Hona hemen zure 1 minutuko laburpena',
    be: 'Вось твой 1 minute рэзюмэ',
    ht: 'Men rezime 1 minute ou',
    mi: 'Anei tō kōrero whakarāpopoto mō te 1 minute',
    sm: 'O lau fa\'amatalaga pu\'upu\'u mo le 1 minute',
    haw: 'Eia kāu 1 minute recap',
    bo: 'འདི་ག་རེས་ཁྱེད་རང་གི་དུས་ཚོད 1 སྐར་མའི་རྩོམ་བརྗོད་རེད།',
    eo: 'Jen via 1-minuta resumo',
    lb: 'Hei ass däi 1 Minute Resumé',
    co: 'Eccu u to riassuntu di 1 minute',
    su: 'Ieu ringkesan 1 menit anjeun',
    jv: 'Iki ringkesan 1 menit kanggo sampeyan',
    ceb: 'Aniya ang imong 1 minute recap',
    gd: 'Seo agad an ath-shealladh 1 minute agad',
    tt: 'Менә синең 1 минутлык кыскача аңлатма',
    tk: 'Ine, seniň 1 minute jemleýjiň',
    wo: 'Nii laa la jëfandikoo 1 minute',
    ti: 'እዚ እዚ ንሓደ ደቂቕ ምስጢር እዩ',
    om: 'Kun gabaasa 1 daqiiqaa kee',
    sd: 'هتي آهي تنهنجو 1 minute جو خلاصو',
    fj: 'Oqo na nomu vakadodonutaki ni 1 minute',
    to: 'Kuo \'osi heni ho\'o fakamatala fakafuofua 1 minute',
  },

  /* ── Chat greeting bubble — friendly intro ── */
  chatGreeting: {
    en: 'Hey! I\'ve watched the full video. Ask me anything. Key moments, context, opinions, or anything you missed.',
    fa: 'سلام! من کل ویدیو رو دیدم. هر چی می‌خوای بپرس. لحظات کلیدی، زمینه، نظرات، یا هر چیزی که از دست دادی.',
    es: '¡Hola! He visto el video completo. Pregúntame lo que quieras. Momentos clave, contexto, opiniones o cualquier cosa que te hayas perdido.',
    pt: 'Ei! Assisti ao vídeo completo. Pergunta o que quiser. Momentos chave, contexto, opiniões ou qualquer coisa que você perdeu.',
    fr: 'Salut ! J\'ai regardé toute la vidéo. Demande-moi ce que tu veux. Moments clés, contexte, avis, ou tout ce que tu as manqué.',
    zh: '嗨！我看完了整个视频。问我任何问题吧。关键时刻、背景信息、观点，或者你错过的任何内容。',
    de: 'Hey! Ich habe das ganze Video gesehen. Frag mich alles. Wichtige Momente, Kontext, Meinungen oder alles, was du verpasst hast.',
    ja: 'やあ！動画を全部見たよ。何でも聞いてね。重要な瞬間、コンテキスト、意見、見逃したこととか何でも。',
    ko: '안녕! 내가 전체 영상을 봤어. 뭐든 물어봐. 중요한 순간들, 컨텍스트, 의견, 놓친 것들 뭐든지.',
    hi: 'अरे! मैंने पूरा वीडियो देखा है। मुझसे कुछ भी पूछो। मुख्य क्षण, संदर्भ, राय, या कुछ भी जो तुमसे छूट गया हो।',
    ar: 'مرحبًا! شاهدت الفيديو بالكامل. اسألني عن أي شيء. اللحظات المهمة، السياق، الآراء، أو أي شيء فاتك.',
    ru: 'Привет! Я посмотрел всё видео. Спрашивай что угодно. Ключевые моменты, контекст, мнения или что-то, что ты пропустил.',
    it: 'Ehi! Ho guardato l\'intero video. Chiedimi qualsiasi cosa. Momenti chiave, contesto, opinioni o qualsiasi cosa ti sia sfuggita.',
    tr: 'Merhaba! Tüm videoyu izledim. Bana her şeyi sorabilirsin. Önemli anlar, bağlam, görüşler veya kaçırdığın herhangi bir şey.',
    nl: 'Hey! Ik heb de hele video bekeken. Vraag me maar wat je wilt. Belangrijke momenten, context, meningen, of iets wat je gemist hebt.',
    pl: 'Cześć! Obejrzałem cały film. Pytaj o cokolwiek. Kluczowe momenty, kontekst, opinie, czy coś, co przegapiłeś.',
    sv: 'Hej! Jag har kollat på hela videon. Fråga mig vad som helst. Viktiga ögonblick, sammanhang, åsikter eller något du missade.',
    da: 'Hej! Jeg har set hele videoen. Spørg mig om hvad som helst. Vigtige øjeblikke, kontekst, meninger eller noget du gik glip af.',
    fi: 'Hei! Katsoin koko videon. Kysy mitä tahansa. Tärkeät hetket, konteksti, mielipiteet tai mitä tahansa, mitä jäit kaipaamaan.',
    no: 'Hei! Jeg har sett hele videoen. Spør meg om hva som helst. Nøkkeløyeblikk, kontekst, meninger, eller noe du gikk glipp av.',
    el: 'Γεια! Είδα όλο το βίντεο. Ρώτα με ό,τι θες. Σημαντικές στιγμές, πλαίσιο, απόψεις ή οτιδήποτε έχασες.',
    he: 'היי! צפיתי בכל הסרטון. תשאל אותי כל מה שבא לך. רגעים חשובים, הקשר, דעות, או כל דבר שפספסת.',
    th: 'สวัสดี! เราดูวิดีโอทั้งหมดแล้ว ถามได้เลย ไม่ว่าจะเป็นช่วงสำคัญ บริบท ความคิดเห็น หรืออะไรที่คุณพลาดไป',
    vi: 'Chào bạn! Mình đã xem toàn bộ video. Hỏi mình bất cứ điều gì nhé. Những khoảnh khắc quan trọng, ngữ cảnh, ý kiến, hay bất cứ điều gì bạn bỏ lỡ.',
    id: 'Hai! Aku sudah nonton videonya. Tanya apa saja. Momen penting, konteks, pendapat, atau apa pun yang kamu lewatkan.',
    ms: 'Hai! Aku dah tonton video penuh. Tanya je apa-apa. Detik penting, konteks, pendapat, atau apa-apa yang kamu terlepas.',
    uk: 'Привіт! Я подивився все відео. Запитай мене про що завгодно. Ключові моменти, контекст, думки або щось, що ти пропустив.',
    cs: 'Ahoj! Viděl jsem celé video. Zeptej se mě na cokoliv. Klíčové momenty, kontext, názory, nebo cokoliv, co ti uniklo.',
    ro: 'Hei! Am văzut tot videoclipul. Întreabă-mă orice. Momente cheie, context, opinii sau orice ai ratat.',
    hu: 'Szia! Megnéztem a teljes videót. Kérdezz bármit. Kulcsmomentumok, környezet, vélemények, vagy bármi, amit kihagytál.',
    bg: 'Здрасти! Гледах цялото видео. Питай ме всичко. Ключови моменти, контекст, мнения или нещо, което си изпуснал.',
    hr: 'Hej! Pogledao sam cijeli video. Pitaj me bilo što. Ključni trenuci, kontekst, mišljenja ili bilo što što si propustio.',
    sk: 'Ahoj! Pozrel som si celé video. Pýtaj sa čokoľvek. Kľúčové momenty, kontext, názory, alebo čokoľvek, čo si premeškal.',
    sr: 'Ćao! Pogledao sam ceo video. Pitaj me bilo šta. Ključni trenuci, kontekst, mišljenja ili bilo šta što si propustio.',
    bn: 'হেই! আমি পুরো ভিডিওটা দেখেছি। কিছু জানতে চাও? গুরুত্বপূর্ণ মুহূর্ত, প্রেক্ষাপট, মতামত, বা কিছু মিস করেছো কি?',
    ta: 'ஹே! நான் முழு வீடியோவையும் பார்த்தேன். என்னவென்றாலும் கேளு. முக்கிய தருணங்கள், சூழல், கருத்துக்கள், அல்லது நீ தவறவிட்டது ஏதாவது.',
    ur: 'ارے! میں نے پوری ویڈیو دیکھی ہے۔ کچھ بھی پوچھ لو۔ اہم لمحات، سیاق و سباق، رائے، یا کچھ بھی جو تم سے رہ گیا ہو۔',
    fil: 'Uy! Napanood ko ang buong video. Tanungin mo ako ng kahit ano. Mga mahalagang sandali, konteksto, opinyon, o anumang hindi mo napanood.',
    sw: 'Mambo! Nimeangalia video yote. Uliza chochote. Matukio muhimu, muktadha, maoni, au chochote ulichokosa.',
    ca: 'Ei! He vist tot el vídeo. Pregunta\'m el que vulguis. Moments clau, context, opinions o qualsevol cosa que t\'hagis perdut.',
    af: 'Hey! Ek het die hele video gekyk. Vra my enigiets. Sleutelmomente, konteks, opinies, of enigiets wat jy gemis het.',
    et: 'Hei! Ma vaatasin kogu video ära. Küsi minult mida iganes. Olulised hetked, kontekst, arvamused või midagi, millest ilma jäid.',
    lv: 'Čau! Es noskatījos visu video. Jautā man jebko. Galvenie momenti, konteksts, viedokļi vai kaut kas, ko palaidi garām.',
    lt: 'Labas! Peržiūrėjau visą vaizdo įrašą. Klausk, ko tik nori. Pagrindiniai momentai, kontekstas, nuomonės ar kas nors, ką praleidai.',
    sl: 'Hej! Pogledal sem celoten video. Vprašaj me karkoli. Ključni trenutki, kontekst, mnenja ali karkoli, kar si zgrešil.',
    te: 'హే! నేను మొత్తం వీడియో చూశాను. నన్ను ఏదైనా అడుగు. ముఖ్య క్షణాలు, సందర్భం, అభిప్రాయాలు లేదా నువ్వు మిస్ అయిన ఏదైనా.',
    mr: 'अरे! मी पूर्ण व्हिडिओ पाहिलाय. काहीही विचार. महत्वाचे क्षण, संदर्भ, मते, किंवा काही चुकले असेल तर.',
    gu: 'હાય! મેં આખું વિડિયો જોયું છે. મને કશું પણ પૂછો. મુખ્ય ક્ષણો, સંદર્ભ, અભિપ્રાયો, અથવા તમે જે ચૂકી ગયા હોય તે.',
    kn: 'ಹೇ! ನಾನು ಸಂಪೂರ್ಣ ವೀಡಿಯೊ ನೋಡಿದ್ದೇನೆ. ಏನಾದರೂ ಕೇಳು. ಮುಖ್ಯ ಕ್ಷಣಗಳು, ಸನ್ನಿವೇಶ, ಅಭಿಪ್ರಾಯಗಳು, ಅಥವಾ ನೀನು ತಪ್ಪಿಸಿದ ಏನಾದರೂ.',
    ml: 'ഹേയ്! ഞാൻ മുഴുവൻ വീഡിയോയും കണ്ടു. എന്തെങ്കിലും ചോദിക്കൂ. പ്രധാന നിമിഷങ്ങൾ, സന്ദർഭം, അഭിപ്രായങ്ങൾ, അല്ലെങ്കിൽ നീ നഷ്ടപ്പെട്ടത് എന്തെങ്കിലും.',
    pa: 'ਹੈਲੋ! ਮੈਂ ਪੂਰੀ ਵੀਡੀਓ ਦੇਖ ਲਈ ਹੈ। ਕੁਝ ਵੀ ਪੁੱਛੋ। ਮੁੱਖ ਪਲ, ਸੰਦਰਭ, ਰਾਏ, ਜਾਂ ਜੋ ਕੁਝ ਵੀ ਤੁਸੀਂ ਛੱਡ ਦਿੱਤਾ।',
    si: 'ආයුබෝවන්! මම සම්පූර්ණ වීඩියෝව බැලුවා. මට ඕන දෙයක් අහන්න. ප්‍රධාන අවස්ථා, පසුබිම, අදහස්, හෝ ඔයාට අහිමි වුන දෙයක්.',
    ne: 'हे! मैले पूरा भिडियो हेरेँ। केही पनि सोध्न सक्छौ। मुख्य क्षणहरू, सन्दर्भ, विचारहरू, वा केही छुट्यो भने।',
    my: 'ဟေး! ငါဗီဒီယိုအပြည့်ကိုကြည့်ပြီးပြီ။ ဘာမေးမေးမေးလို့ရတယ်။ အဓိကအချက်များ၊ အကြောင်းအရာ၊ အမြင်များ၊ သို့မဟုတ် မင်းလွတ်ခဲ့တာတွေကိုမေးပါ။',
    km: 'សួស្តី! ខ្ញុំបានមើលវីដេអូទាំងស្រុងហើយ។ សួរអ្វីក៏បាន។ ពេលវេលាសំខាន់ៗ បរិបទ មតិ ឬអ្វីដែលអ្នកខកខាន។',
    lo: 'ສະບາຍດີ! ຂ້ອຍໄດ້ເບິ່ງວິດີໂອທັງໝົດແລ້ວ. ຖາມຂ້ອຍໄດ້ເລີຍ. ຈຸດສຳຄັນ, ບົດບາດ, ຄວາມຄິດເຫັນ, ຫຼືສິ່ງທີ່ເຈົ້າພາດ.',
    'zh-TW': '嗨！我看完了整部影片。隨便問我什麼吧。重點時刻、背景資訊、意見，或是你錯過的任何東西。',
    mn: 'Сайн уу! Би бүх видеог үзсэн. Надаас юу ч асуугаарай. Гол мөчүүд, агуулга, санал бодол, эсвэл алгассан зүйлс.',
    ku: 'Hey! Ew vidyoya tevahî temaşekirîme. Ji min her tiştî bipirse. Waqtên serekeyî, naverok, fikir, an tiştên ku tu ji dest derxistî.',
    az: 'Salam! Mən tam videoya baxmışam. Mənə hər şeyi soruşa bilərsən. Əsas məqamlar, kontekst, fikirlər və ya qaçırdığın hər hansı bir şey.',
    uz: 'Salom! Men butun videoni ko\'rdim. Nima bo\'lsa so\'ra. Muhim lahzalar, kontekst, fikrlar yoki o\'tkazib yuborgan narsalaring.',
    kk: 'Сәлем! Мен бүкіл видеоны көріп шықтым. Қандай сұрағың бар? Негізгі сәттер, контекст, пікірлер немесе жіберіп алған нәрселерің туралы сұра.',
    ky: 'Салам! Мен толук видеону көрдүм. Эмне болсо да сура. Негизги учурлар, контекст, пикирлер же өткөрүп жиберген нерселериң.',
    tg: 'Салом! Ман тамоми видеоро тамошо кардам. Аз ман ҳар чизе пурс. Лаҳзаҳои муҳим, мазмун, фикрҳо ё чизе, ки ту аз даст додӣ.',
    ka: 'ჰეი! ვუყურე მთელ ვიდეოს. მკითხე რაც გინდა. მთავარი მომენტები, კონტექსტი, აზრები ან რამე რაც გამოგრჩა.',
    hy: 'Ողջույն! Ես նայել եմ ամբողջ վիդեոն։ Հարցրու ինձ ինչ ուզում ես։ Հիմնական պահեր, կոնտեքստ, կարծիքներ, կամ ինչ որ բաց ես թողել։',
    ps: 'سلام! ما ټول ویډیو کتلې ده. هر څه چې غواړې وپوښته. مهمې شیبې، سیاق و سباق، نظرونه، یا هر څه چې دې له لاسه ورکړي وي.',
    am: 'ሰላም! ሙሉውን ቪዲዮ አይቻለሁ። ምንም ነገር ጠይቀኝ። ቁልፍ አስቀድሞች, እንቅስቃሴ, አስተያየቶች, ወይም ያልተያዘው ማንኛውም ነገር።',
    ha: 'Sannu! Na kalli dukkan bidiyon. Tambaye ni komai. Muhimman lokuta, mahallin, ra\'ayoyi, ko duk wani abu da ka rasa.',
    yo: 'Báwo! Mo ti wo gbogbo fíìmù náà. Béèrè ohunkóhun. Àwọn ìṣẹ̀lẹ̀ pàtàkì, àkóónú, èrò, tàbí ohunkóhun tí o kù.',
    ig: 'Nnoo! Ekwuru m vidio ahụ dum. Jụọ m ihe ọ bụla. Ihe ndị dị mkpa, ihe gbasara, echiche, ma ọ bụ ihe ọ bụla ị hapụrụ.',
    zu: 'Sawubona! Ngibukele ividiyo yonke. Buza noma yini. Izikhathi ezibalulekile, uhlaka, imibono, noma yini oyiphuthele.',
    xh: 'Molo! Ndiyibukele yonke ividiyo. Ndibuze nantoni na. Iziganeko eziphambili, umxholo, izimvo, okanye nantoni na oyiphoseleyo.',
    so: 'Salaan! Waxaan daawaday fiidiyowga oo dhan. Weydii wax kasta. Xilliyada muhiimka ah, macnaha guud, fikradaha, ama wax kasta oo aad ka maqnaatay.',
    rw: 'Mwaramutse! Narebye videwo yose. Mbaza icyo ushaka. Ibintu by\'ingenzi, amakuru, ibitekerezo, cyangwa icyo waba waracikanywe.',
    mg: 'Hey! Nijery ny horonan-tsary manontolo aho. Anontanio ahy izay rehetra tianao. Fotoana lehibe, toe-javatra, hevitra, na izay rehetra tsy hitanao.',
    sq: 'Hej! E kam parë të gjithë videon. Pyet çfarë të duash. Momente kyçe, kontekst, mendime, ose çfarëdo që ke humbur.',
    mk: 'Здраво! Го изгледав целиот видео. Прашај ме што сакаш. Клучни моменти, контекст, мислења или нешто што си пропуштил.',
    bs: 'Hej! Pogledao sam cijeli video. Pitaj me bilo šta. Ključni trenuci, kontekst, mišljenja ili bilo šta što si propustio.',
    is: 'Hæ! Ég hef horft á allt myndbandið. Spurðu mig um hvað sem er. Lykilatriði, samhengi, skoðanir, eða eitthvað sem þú misstir af.',
    mt: 'Ħej! Rajt il-video kollu. Staqsini xi ħaġa. Mumenti ewlenin, kuntest, opinjonijiet, jew xi ħaġa li tlift.',
    ga: 'Haigh! D\'fhéach mé ar an bhfíseán iomlán. Fiafraigh díom rud ar bith. Príomhchuimhneacháin, comhthéacs, tuairimí, nó aon rud a chaill tú.',
    cy: 'Hei! Dw i wedi gwylio\'r fideo cyfan. Gofyn unrhyw beth i mi. Eiliadau allweddol, cyd-destun, barn, neu unrhyw beth wyt ti wedi colli.',
    gl: 'Ola! Vin o vídeo completo. Pregúntame o que queiras. Momentos clave, contexto, opinións ou calquera cousa que te perderas.',
    eu: 'Kaixo! Bideo osoa ikusi dut. Galdetu nahi duzuna. Une garrantzitsuak, testuingurua, iritziak edo galdu duzun edozer.',
    be: 'Прывітанне! Я паглядзеў усё відэа. Спытай у мяне што заўгодна. Асноўныя моманты, кантэкст, меркаванні ці ўсё, што ты прапусціў.',
    ht: 'Hey! Mwen gade tout videyo a. Mande m\' nenpòt bagay. Moman kle, kontèks, opinyon, oswa nenpòt bagay ou rate.',
    mi: 'Kia ora! Kua mātakitaki au i te ataata katoa. Pātai mai, ahakoa he aha. Ngā wā nui, horopaki, whakaaro, me ngā mea i ngaro i a koe.',
    sm: 'Talofa! Ua ou matamata i le vitio atoa. Fesili mai i so\'o se mea. O taimi taua, fa\'amatalaga, manatu, po\'o so\'o se mea na e misia.',
    haw: 'Aloha! Ua nānā au i ke wikiō holoʻokoʻa. Nīnau mai i kekahi mea. Nā manawa koʻikoʻi, kūlana, manaʻo, a i ʻole kekahi mea āu i hala ai.',
    bo: 'ཨ་ནི། ངས་བརྙན་ཐུང་ཆ་ཚང་བལྟ་ཡོད། ག་རེ་ཡང་དྲིས་རོགས། གནད་དོན་དང་སྐབས་བཅད། བསམ་བློ་དང་ག་རེ་ཡང་བརྙེས་མ་ཐུབ།',
    eo: 'Hej! Mi spektis la tutan videon. Demandu min ion ajn. Ĉefaj momentoj, kunteksto, opinioj, aŭ io ajn, kion vi maltrafis.',
    lb: 'Moien! Ech hunn de ganze Video gekuckt. Frot mech alles. Schlësselmomenter, Kontext, Meenungen oder eppes wat\'s de verpasst hues.',
    co: 'Ehi! Aghju vistu tuttu u video. Dumandami tuttu ciò chì voli. Momenti chjave, cuntestu, opinioni, o tuttu ciò chì ti hè sfughjitu.',
    su: 'Hey! Kuring geus nonton video lengkepna. Tanya naon wae ka kuring. Momen penting, konteks, opini, atawa naon wae anu teu katingali.',
    jv: 'Hai! Aku wis nonton video iki kabeh. Takon wae apa wae. Momen penting, konteks, pendapat, utawa apa wae sing kowe ora ngerti.',
    ceb: 'Hoy! Nakita nako ang tibuok video. Pangutan-a ko bisan unsa. Mga importante nga higayon, konteksto, opinyon, o bisan unsa nga imong nalaktawan.',
    gd: 'Hey! Tha mi air a’ bhidio gu lèir fhaicinn. Faighnich dhomh rud sam bith. Prìomh mhionaidean, co-theacsa, beachdan, no rud sam bith a chaill thu.',
    tt: 'Сәлам! Мин бөтен видеоны карадым. Нәрсә булса да сора. Төп мизгелләр, контекст, фикерләр, яки син үткәреп җибәргән әйберләр.',
    tk: 'Salam! Men wideoň dolusyny gördüm. Maňa islendik zady sorap bilersiň. Açar pursatlar, kontekst, pikirler ýa-da sypdyran zatlaryň.',
    wo: 'Nanga def! Damay seet video bi lépp. Laajal ma lu nekk. Mooment yu am solo, njuumte, xalaat, walla lu la gën a jàpp.',
    ti: 'ሰላም! እቲ ቪድዮ ኣብ ሙሉኡ ተርኢኹም። ንሕነ እቲ ኣርእስቲ ኣርእስቲ፣ እቲ እትሕብር፣ ርእይቶታት ወይ እቲ ዝተንእሰዎ ኣነኹም።',
    om: 'Akkam! Viidiyoo guutuu nan ilaale. Waa\'ee kamiyyuu na gaafadhu. Yeroo ijoo, seensa, yaada, yookaan waan siif dhokate.',
    sd: 'هاءِ! مون سڄي وڊيو ڏٺي آهي. مون کان ڪجھ به پڇو. اهم لمحات، پسمنظر، رايا، يا ڪجھ به جيڪو توکي مس ٿيو.',
    fj: 'Bula! Au sa raica oti na vidio taucoko. Taroga mada vei au e dua na ka. Na veika bibi, itukutuku, nanuma, se dua na ka o a calata.',
    to: 'Mālō e lelei! Na\'a ku mamata ki he vitio kakato. Fai ha\'o fehu\'i kiate au. Ngaahi taimi mahu\'inga, kontekisi, ngaahi fakakaukau, pe ha me\'a na\'e misi ai koe.',
  },

  /* ── Music-only video — small badge near the top of summary/chapters
        when the transcript is dominated by [Music]/[Applause] annotations.
        Hand-seeded for ~25 common languages; full coverage via
        `scripts/regenerate_ui_strings.py` in a future pass. */
  musicOnlyBadge: {
    en: 'Mostly music — limited spoken content',
    fa: 'بیشتر موسیقی — محتوای گفتاری محدود',
    es: 'Principalmente música — contenido hablado limitado',
    pt: 'Principalmente música — conteúdo falado limitado',
    fr: 'Principalement de la musique — contenu parlé limité',
    de: 'Hauptsächlich Musik — begrenzter gesprochener Inhalt',
    it: 'Per lo più musica — contenuto parlato limitato',
    ja: '主に音楽 — 話し声の内容は限られています',
    zh: '主要是音乐 — 口语内容有限',
    ko: '주로 음악 — 음성 콘텐츠 제한적',
    ar: 'موسيقى في الغالب — محتوى منطوق محدود',
    he: 'בעיקר מוזיקה — תוכן מדובר מוגבל',
    ru: 'В основном музыка — ограниченный речевой контент',
    hi: 'ज़्यादातर संगीत — सीमित बोला गया कंटेंट',
    tr: 'Çoğunlukla müzik — sınırlı konuşma içeriği',
    nl: 'Voornamelijk muziek — beperkte gesproken inhoud',
    pl: 'Głównie muzyka — ograniczona zawartość mówiona',
    sv: 'Mestadels musik — begränsat talat innehåll',
    da: 'Mest musik — begrænset talt indhold',
    fi: 'Pääosin musiikkia — rajallinen puhesisältö',
    no: 'Mest musikk — begrenset talt innhold',
    el: 'Κυρίως μουσική — περιορισμένο προφορικό περιεχόμενο',
    th: 'เพลงเป็นส่วนใหญ่ — เนื้อหาพูดจำกัด',
    vi: 'Chủ yếu là nhạc — nội dung nói hạn chế',
    id: 'Kebanyakan musik — konten lisan terbatas',
    uk: 'Переважно музика — обмежений мовний контент',
  },

  /* ── Music-only video — placeholder shown in transcript/subtitle tab
        instead of the [Music] [Music] [Music]… repetition. ── */
  musicOnlyTitle: {
    en: 'This video is mostly music',
    fa: 'این ویدیو بیشتر موسیقی است',
    es: 'Este vídeo es principalmente música',
    pt: 'Este vídeo é principalmente música',
    fr: 'Cette vidéo est principalement musicale',
    de: 'Dieses Video besteht hauptsächlich aus Musik',
    it: 'Questo video è per lo più musica',
    ja: 'このビデオは主に音楽です',
    zh: '此视频主要是音乐',
    ko: '이 동영상은 대부분 음악입니다',
    ar: 'هذا الفيديو موسيقي في الغالب',
    he: 'הסרטון הזה הוא בעיקר מוזיקה',
    ru: 'Это видео в основном музыка',
    hi: 'यह वीडियो ज़्यादातर संगीत है',
    tr: 'Bu video çoğunlukla müzik',
    nl: 'Deze video is voornamelijk muziek',
    pl: 'To wideo to głównie muzyka',
    sv: 'Den här videon är mestadels musik',
    da: 'Denne video er mest musik',
    fi: 'Tämä video on pääosin musiikkia',
    no: 'Denne videoen er mest musikk',
    el: 'Αυτό το βίντεο είναι κυρίως μουσική',
    th: 'วิดีโอนี้ส่วนใหญ่เป็นเพลง',
    vi: 'Video này chủ yếu là nhạc',
    id: 'Video ini sebagian besar musik',
    uk: 'Це відео переважно музика',
  },
  musicOnlySub: {
    en: 'There\'s no real spoken content to transcribe.',
    fa: 'محتوای گفتاری واقعی برای رونویسی وجود ندارد.',
    es: 'No hay contenido hablado real para transcribir.',
    pt: 'Não há conteúdo falado real para transcrever.',
    fr: 'Il n\'y a pas de contenu parlé réel à transcrire.',
    de: 'Es gibt keinen echten gesprochenen Inhalt zum Transkribieren.',
    it: 'Non c\'è contenuto parlato reale da trascrivere.',
    ja: '文字起こしする実際の話し声はありません。',
    zh: '没有真实的口语内容可转录。',
    ko: '전사할 실제 음성 콘텐츠가 없습니다.',
    ar: 'لا يوجد محتوى منطوق فعلي للنسخ.',
    he: 'אין תוכן מדובר אמיתי לתמלול.',
    ru: 'Нет настоящей речи для транскрипции.',
    hi: 'लिप्यंतरण के लिए कोई वास्तविक बोला गया कंटेंट नहीं है।',
    tr: 'Yazıya dökülecek gerçek konuşma içeriği yok.',
    nl: 'Er is geen echte gesproken inhoud om te transcriberen.',
    pl: 'Brak prawdziwej zawartości mówionej do transkrypcji.',
    sv: 'Det finns inget riktigt talat innehåll att transkribera.',
    da: 'Der er intet rigtigt talt indhold at transskribere.',
    fi: 'Ei oikeaa puhesisältöä litteroitavaksi.',
    no: 'Det er ingen ekte talt innhold å transkribere.',
    el: 'Δεν υπάρχει πραγματικό προφορικό περιεχόμενο για μεταγραφή.',
    th: 'ไม่มีเนื้อหาที่พูดจริงให้ถอดความ',
    vi: 'Không có nội dung nói thực sự để chuyển ngữ.',
    id: 'Tidak ada konten lisan nyata untuk ditranskripsi.',
    uk: 'Немає справжнього мовного вмісту для транскрипції.',
  },
};

/**
 * Resolve a UI string for the given language, with English fallback.
 * Accepts region variants (e.g. 'fa-IR' → falls back to 'fa').
 */
export function uiString(key, lang) {
  const map = UI_STRINGS[key];
  if (!map) return '';
  if (!lang) return map.en || '';
  if (map[lang]) return map[lang];
  const base = lang.split('-')[0];
  if (map[base]) return map[base];
  return map.en || '';
}
