"""add sheet_connections table

Revision ID: 7ab0f7a76dd5
Revises: 0580d3c52ad9
Create Date: 2026-05-08 14:04:16.437522

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# Revision identifiers, used by Alembic.
revision: str = '7ab0f7a76dd5'
down_revision: str | None = '0580d3c52ad9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spreadsheet_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('worksheet_title', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sheet_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sheet_connections_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sheet_connections_user_id'))

    op.drop_table('sheet_connections')
    # ### end Alembic commands ###
